Add From<(VecN-1, f32)> for VecN
bitshifter/glam-rs pull request #103
Opened 2020-12-03 08:49 UTC by XAMPPRocky

This PR adds some convenience `From` impls that allow you concat a tuple of a vector with a f32 into the next biggest vector similar to GLSL's initialisers such as `vec4(vec3, w)` without having to write out every coordinate.

```rust
let v2 = Vec2::from((1.0, 2.0));
let v3 = Vec3::from((v2, 3.0));
let v4 = Vec4::from((v3, 4.0));
```

2020-12-06 09:06 UTC, bitshifter requested changes
Seems like a good solution, I waver between using From and more explicit functions sometimes because I think explicit functions are a bit more discoverable. This seems fine though.

Happy to merge this but I'd like tests for these new methods..

2020-12-08 22:25 UTC, XAMPPRocky commented
@bitshifter Updated with tests.

2020-12-09 10:57 UTC, merged

2020-12-09 10:57 UTC, bitshifter commented
Thanks!

2020-12-10 08:15 UTC, Boscop commented
Could you please also add `From<{Vec2, Vec2)> for Vec4`? :)