Add i64/u64 vector types
bitshifter/glam-rs pull request #378
Opened 2023-02-24 16:35 UTC by BeastLe9enD

Hey, I added i64/u64 vector types called `LVecN` / `ULVecN` ( I chose this naming to make it fit with the other types that exist so far ).
The reason why I add these types is that I want to support Int64 vectors in Rust GPU.

2023-02-24 22:35 UTC, bitshifter commented
Have you discussed i64 support with the rust-gpu team? If so are they receptive to the change?

2023-02-24 22:43 UTC, BeastLe9enD commented
@bitshifter Oh yea, good point.I asked in their discord if they are receptive, I will let you know if there is anything new!

2023-02-27 04:54 UTC, bitshifter commented
Seems like rust-gpu might want it, pending some devs being away. Naming wise, I have tended to stick with naming similar to GLSL or GLM. While there aren't i64 or u64 vectors in GLSL, there is in an ARB extension - https://registry.khronos.org/OpenGL/extensions/ARB/ARB_gpu_shader_int64.txt. In this extension they use `i64vec*` and `u64vec*`, so in `glam` my preference naming wise would be match that and use `I64Vec*` and `U64Vec*`.

2023-02-27 15:43 UTC, BeastLe9enD commented
Okay, fair. I renamed them to I64VecN/U64VecN :)

2023-03-04 00:46 UTC, bitshifter requested changes

2023-03-04 16:57 UTC, BeastLe9enD commented on codegen/templates/vec.rs.tera
> +{% if scalar_t == "f64" or scalar_t == "i64" or scalar_t == "u64" or dim == 4 %}
Im not sure tbh, I have never worked with CUDA. I just assumed it because the size of the type

2023-03-06 02:10 UTC, bitshifter commented on codegen/templates/vec.rs.tera
> +{% if scalar_t == "f64" or scalar_t == "i64" or scalar_t == "u64" or dim == 4 %}
Looks like it's right, I think https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#built-in-vector-types.

2023-03-06 02:11 UTC, bitshifter approved these changes

2023-03-07 04:00 UTC, merged

2023-03-07 04:00 UTC, bitshifter commented
I didn't see any further comments on Embark discord, so merged as is. Thanks!