Add `rotate_towards` for `Vec2` and `Quat`
bitshifter/glam-rs pull request #495
Opened 2024-03-14 21:19 UTC by chompaa

Adds a `rotate_towards` function for `Vec2` and `Quat`, based on discussion in #265, with tests.

I'm unsure if these tests are comprehensive enough.

2024-03-17 19:17 UTC, bitshifter commented
It might take a while before I have time to have a proper look at this.

2024-05-19 05:13 UTC, bitshifter requested changes
Just some minor docs changes.

2024-05-19 05:13 UTC, bitshifter commented on codegen/templates/vec.rs.tera
> +    /// Rotates towards `rhs` based on the value `d`.
Should also mention that d is an angle in radians.

2024-05-22 21:02 UTC, chompaa commented on codegen/templates/quat.rs.tera
> +    /// Rotates towards `rhs` based on the value `d`.
Would this suffice?
```rs
/// Rotates towards `rhs` by `d` radians.
```

2024-05-23 10:38 UTC, bitshifter commented on codegen/templates/quat.rs.tera
> +    /// Rotates towards `rhs` based on the value `d`.
Actually don't worry about it, it's probably easier for me to merge and make docs changes.

2024-05-23 10:38 UTC, merged