Make random quaternions uniformly random (via `Standard`)
bitshifter/glam-rs pull request #534
Opened 2024-07-05 13:30 UTC by mweatherley

Previously, randomly sampled `Quat`s had bias because they were constructed using Euler rotation sequences. This PR makes them follow a uniform distribution. The algorithm used is the one found [here](https://web.archive.org/web/20180724074257/http://planning.cs.uiuc.edu/node198.html). 

This is essentially a follow-up from [this bevy_math PR](https://github.com/bevyengine/bevy/pull/12857), which affords users the ability to ergonomically obtain random directions and quaternions.

I believe that this implementation also conforms more closely with the philosophy of [Standard](https://docs.rs/rand/latest/rand/distributions/struct.Standard.html): since the space of quaternions is compact, it is quite natural for the "default" distribution over them to be uniform. 

Furthermore, if a user wants the old distribution, it is easily implemented using just `rand::gen_range` and `Quat`'s constructors; the present implementation actually bundles relatively specialized knowledge into an interface, which abstracts difficulties away from users.

2024-07-05 13:34 UTC, NthTensor commented
Over at bevy we've had several users be confused when they encounter the current nonuniform version. We can't really fix this in our side, and to me this seems like a better default.

2024-07-05 20:46 UTC, bitshifter approved these changes

2024-07-05 20:47 UTC, bitshifter commented
You need to use `math::sin_cos` which wraps libm and std implementations.

2024-07-05 21:08 UTC, ickk requested changes
I compared this PR to a few other approaches

The prng used was `rand::rngs::SmallRng`

```
rand_quat/existing      time:   [1.2494 ns 1.2528 ns 1.2561 ns]
rand_quat/subgroup      time:   [2.3529 ns 2.3573 ns 2.3618 ns]
rand_quat/sphere_inline time:   [1.8076 ns 1.8121 ns 1.8167 ns]
rand_quat/hatbox        time:   [1.2487 ns 1.2517 ns 1.2548 ns]
```

<details>
<summary>Code</summary>

```rust
#[inline]
pub fn existing<R: Rng>(rng: &mut R) -> Quat {
    rng.gen()
}

#[inline]
pub fn subgroup<R: Rng>(rng: &mut R) -> Quat {
    let (s1, c1) = rng.gen_range(0f32..TAU).sin_cos();
    let (s2, c2) = rng.gen_range(0f32..TAU).sin_cos();

    let x0 = rng.gen_range(0f32..1.);
    let (r1, r2) = (x0.sqrt(), (1. - x0).sqrt());

    Quat::from_xyzw(s1 * r1, c1 * r1, s2 * r2, c2 * r2)
}

#[inline]
pub fn sphere_inline<R: Rng>(rng: &mut R) -> Quat {
    let phi_cos = rng.gen_range(-1f32..=1.0);
    let phi_sin = phi_cos.acos().sin();
    let (theta_sin, theta_cos) = rng.gen_range(0f32..=TAU).sin_cos();

    let axis: Vec3 = Vec3::new(phi_sin * theta_cos, phi_sin * theta_sin, phi_cos);
    let angle = rng.gen_range(-TAU..=TAU);

    Quat::from_axis_angle(axis, angle)
}

#[inline]
pub fn hatbox<R: Rng>(rng: &mut R) -> Quat {
    let z = rng.gen_range(-1.0..=1.0);
    let (a_sin, a_cos) = rng.gen_range(-PI..=PI).sin_cos();
    let c = (1.0-z*z).sqrt();
    let x = a_sin*c;
    let y = a_cos*c;

    let axis = Vec3::new(x, y, z);
    let angle = rng.gen_range(-TAU..=TAU);

    Quat::from_axis_angle(axis, angle)
}
```
</details>

2024-07-06 10:35 UTC, bitshifter commented on src/features/impl_rand.rs
> +                let (sin2, cos2) = rng.gen_range::<$t, _>(0.0..=TAU).sin_cos();
Regarding the test fail, these need to be changed to `math::sin_cos(rng.gen_range::<$t, _>(0.0..=TAU))`

`$t::sqrt` also needs to change to `math::sqrt`, you'll also need to add a `use crate::f32::math` or `use crate::f64::math` in the relevant `mod` block.

2024-07-06 10:47 UTC, bitshifter commented
I don't have a strong feeling about performance characteristics of this. It's something I added at the very beginning of glam to generate some data to run benchmarks on, it's not something I put any thought into at the time. It seems like there's still a bit of discussion happening on bevy discord, let me know what you settle on.

2024-07-14 16:23 UTC, mweatherley commented
Cool. I ended up switching to axis-angle randomization since I think it's simple to grok and its performance seems pretty good.

2024-07-15 07:54 UTC, merged

2024-07-15 07:54 UTC, bitshifter commented
Thanks for the PR!