Generic mapping function for vectors
bitshifter/glam-rs pull request #547
Opened 2024-08-08 07:34 UTC by Aceeri

Hi! Sorry I didn't make a discussion about this first, didn't read the guidelines until I already wrote this up, so figured I might as well post the PR.

This adds a generic mapping function that acts on all of the elements of a vector. Adding it to matrices as well might be useful, but my use cases for this has always just been vectors so far. I'm happy to add it to matrices if you think that'd be good for consistency's sake.

2024-08-08 14:01 UTC, Aceeri commented
https://github.com/bevyengine/bevy/pull/14656/files#diff-0e640ab491c46a3af5c0e6c590467e40376348c3ccb7f4f69612765c96370fc4R381

Another example pointed out by @Jondolf

2024-08-08 21:22 UTC, bitshifter requested changes
I was expecting someone to suggest this eventually :)

One change that I think would make sense is add it for all vector types, not just floating point vectors, I don't think there's any reason not to? This should just be a case of moving the function in codegen to a common area, it would also require tests (which again is mostly a case of moving them to a common location and casting the inputs to the scalar type in the test).

2024-08-08 23:17 UTC, Aceeri commented
> I was expecting someone to suggest this eventually :)
> 
> One change that I think would make sense is add it for all vector types, not just floating point vectors, I don't think there's any reason not to? This should just be a case of moving the function in codegen to a common area, it would also require tests (which again is mostly a case of moving them to a common location and casting the inputs to the scalar type in the test).

Oop ya that makes sense, I had thought this already did this but didn't check.

2024-08-09 02:25 UTC, Aceeri commented
Aaaa not sure what happened here

2024-08-09 02:26 UTC, Aceeri commented
Whoops, did a silly

2024-08-09 10:35 UTC, bitshifter approved these changes

2024-08-09 18:33 UTC, bitshifter commented
Just needs a rust fmt. It would be good if I could auto fmt PRs but I don't think that is possible

2024-08-11 22:28 UTC, merged

2024-08-11 22:28 UTC, bitshifter commented
Thanks for the PR!