Implement manhattan and chebyshev distance for integer vectors
bitshifter/glam-rs pull request #593
Opened 2024-12-20 15:31 UTC by tguichaoua

This implements #415 using the code generator.

2024-12-21 22:52 UTC, bitshifter requested changes
Thanks for the PR.

`abs_diff` on signed integers returns an unsigned integer so this will need a bit more work to code generate that .

The original #415 PR returned the result in a larger sized integer which for the Manhattan distance would help avoid overflow, however I guess for higher dimensions than 2 overflow would still be possible, so I'm not sure it's worth doing that. Also while glam doesn't currently have a `I128Vec*` or `U128Vec*` if they're ever added there is no `u256` primitive in Rust which would make returning a larger integer in with any 128 sizes integer vector not possible. Give that I'm leaning towards your implementation and not returning a larger integer type, but adding a comment to the method pointing out that the result could overflow so that the caller is aware. Do you have any thoughts on how overflow should be handled for these?

Could you also add some tests for these new methods as part of this PR.

2024-12-22 09:42 UTC, tguichaoua commented
> Do you have any thoughts on how overflow should be handled for these?

We should use unsigned integer as return type. As per the documentation of [`abs_diff`](https://doc.rust-lang.org/stable/std/primitive.i8.html#method.abs_diff):
> This function always returns the correct answer without overflow or panics by returning an unsigned integer.

For `manhattan_distance` I added `checked_manhattan_distance` which returns `None` if an overflow would occurs.

2024-12-23 08:18 UTC, bitshifter approved these changes

2024-12-24 03:33 UTC, merged

2024-12-24 03:34 UTC, bitshifter commented
Thanks!